intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{fakeit}: hxx{config/** include/**} $impl_libs $intf_libs

# Export options.
#
lib{fakeit}:
{
  # According to lib it's included as '<fakeit.hpp>' and supporting
  # '<fakeit/fakeit.hpp>' will require a major surgery.
  cxx.export.poptions = "-I$src_base/include" "-I$src_base/config/standalone"
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{fakeit}: bin.lib.version = "-$version.project_id"
else
  lib{fakeit}: bin.lib.version = "-$version.major.$version.minor"

# Install into the fakeit/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/fakeit/
  install.subdirs = true
}
