libs =
import libs += fakeit%lib{fakeit}

# MSVC:
#   Exclude tests that are broken in v2.3.0 (basically the whole test-suite is written for VS 2015 & slightly adjusted for 2019)
#   See:
#   * https://github.com/eranpeer/FakeIt/issues/279
#   * https://github.com/eranpeer/FakeIt/pull/290
#   * etc.

msvc_broken_tests = tests/cpp14_tests.cpp tests/miscellaneous_tests.cpp tests/msc_type_info_tests.cpp tests/spying_tests.cpp tests/stubbing_tests.cpp tests/type_info_tests.cpp tests/verification_tests.cpp
unix_broken_tests = tests/msc_type_info_tests.cpp

exe{fakeit-tests}: {hxx cxx}{tests/** -{$msvc_broken_tests $unix_broken_tests}}
exe{fakeit-tests}: cxx{$msvc_broken_tests}: include = ($cxx.target.class != 'windows')
exe{fakeit-tests}: cxx{$unix_broken_tests}: include = ($cxx.target.class == 'windows')

switch $cxx.class
{
  case 'gcc'
  {
    cxx.coptions += -Wno-ignored-qualifiers
  }
}
