libs =
import libs += fakeit%lib{fakeit}

# MSVC:
#   Exclude tests that are broken in v2.3.0 (basically the whole test-suite is written for VS 2015 & slightly adjusted for 2019)
#   See:
#   * https://github.com/eranpeer/FakeIt/issues/279
#   * https://github.com/eranpeer/FakeIt/pull/290
#   * etc.

if($cxx.id == 'msvc')
{
  broken_tests = tests/cpp14_tests.cpp tests/miscellaneous_tests.cpp tests/msc_type_info_tests.cpp tests/spying_tests.cpp tests/stubbing_tests.cpp tests/type_info_tests.cpp tests/verification_tests.cpp
}
else
{
  broken_tests = tests/msc_type_info_tests.cpp
}

# TODO: How to conditionally exclude sources if VS2019+ & fakeit <= v2.3.0 ?
#
# @@ TODO: this needs to be redone per https://github.com/build2/HOWTO/blob/master/entries/keep-build-graph-config-independent.md
#
exe{fakeit-tests}: {hxx ixx txx cxx}{tests/** -{$broken_tests}} $libs

# Mimic hard-coded flags for tests as done in upstream repo
#
# @@ TODO: things like optimization levels, etc., should not be set
#          by the buildfile. It is Ok to disable warnings.
#
switch $cxx.class
{
  case 'gcc'
  {
    # See: https://github.com/eranpeer/FakeIt/blob/78ca536e6b32f11e2883d474719a447915e40005/tests/CMakeLists.txt#L5
    cxx.coptions += -Wno-ignored-qualifiers #-Wl,--allow-multiple-definition
  }
  case 'msvc'
  {
    # Open all_tests.vcxproj and look through the project properties
    #cxx.coptions += /Gy /Oi
    #cxx.loptions += /OPT:REF
  }
}
